### ISSUE TITLE
no color preview on rgba without 0 before a float.

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-color-codes-preview#10]
I have this piece of code: 

```css
body {
    color: #fff;
    background-color: rgb(0, 0, 0);
    border-color: rgba(0, 0, 0, .9);
    border-color: rgba(0, 0, 0, 0.9);
}
```

and each of them works fine except the first border-color. The problem is that I not write 0.9, I only write it shorter wihout zero: .9. And I can't see a color for this value. I thought rgba was not supported but only the alpha channel has problems with .9. Can you please fix it?
